FROM python
RUN apt update
RUN apt install -y cmake
RUN pip3 install -U pip
RUN pip3 install face_recognition
RUN pip3 install Django==4.0.4 requests==2.27.1 django-oauth-toolkit==1.7.1 xlwt==1.3.0 Pillow==9.1.0
