# Generated by Django 4.0.4 on 2022-06-14 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('token', sloth.db.models.CharField(max_length=255, verbose_name='Token')),
                ('redirect', models.URLField(verbose_name='Redirecionamento')),
                ('usuario', sloth.db.models.CurrentUserField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aplicação',
                'verbose_name_plural': 'Aplicações',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('chave', sloth.db.models.CharField(max_length=255, verbose_name='Chave')),
                ('aplicacao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.aplicacao', verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateField(auto_created=True, verbose_name='Data/Hora')),
                ('latitude', sloth.db.models.CharField(max_length=255, verbose_name='Latitude')),
                ('longitude', sloth.db.models.CharField(max_length=255, verbose_name='Latitude')),
                ('imagem', models.ImageField(upload_to='checkin', verbose_name='Imagem')),
                ('pessoa', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Checkin',
                'verbose_name_plural': 'Checkin',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
