# Generated by Django 4.0.4 on 2022-06-14 10:43

from django.db import migrations, models
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default=None, upload_to='pessoa', verbose_name='Foto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='chave',
            field=sloth.db.models.CharField(help_text='Identificador da pessoa. Ex: E-mail, CPF, Matrícula.', max_length=255, verbose_name='Chave'),
        ),
    ]
