# Generated by Django 4.0.4 on 2022-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_checkin_uuid_alter_checkin_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Foto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pessoa', verbose_name='Foto'),
        ),
    ]
