# Generated by Django 4.0.4 on 2022-06-16 09:14

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_pessoa_url_alter_pessoa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='dispositivo',
            field=sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='token',
            field=sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Token'),
        ),
    ]
