# Generated by Django 4.0.4 on 2022-06-16 21:29

from django.db import migrations
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_pessoa_dispositivo_pessoa_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='longitude',
            field=sloth.db.models.CharField(max_length=255, verbose_name='Longitude'),
        ),
    ]
