# Generated by Django 4.0.4 on 2022-06-18 13:49

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_alter_checkin_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('token', sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('dispositivo', sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Dispositivo')),
                ('raio', models.IntegerField(blank=True, help_text='Distância em metros até onde será possível realizar auto check-in', null=True, verbose_name='Raio')),
                ('latitude', sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', sloth.db.models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('aplicacao', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.aplicacao', verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
