# Generated by Django 4.0.4 on 2022-06-18 16:58

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_remove_aplicacao_redirect_remove_aplicacao_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='ponto',
            field=sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkin.pontocheckin', verbose_name='Ponto'),
        ),
    ]
