# Generated by Django 4.0.4 on 2022-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_checkin_ponto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='data_hora',
            field=models.DateTimeField(auto_created=True, verbose_name='Data/Hora'),
        ),
    ]
