# Generated by Django 4.0.4 on 2022-06-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_solicitacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='checkin',
        ),
    ]
